### PR TITLE
Associate rates with any type of rule

### PR DESCRIPTION
**Pull request by BigIdeas**
Allow any type of rule to have a `rate_amount` field. If a policy has a rule with a `rate_amount`, it must have `rate_recurrence` and `currency` properties.

### CODE REVIEW

**Review by avatarneil — APPROVED** [review]
Rad! I think we ought to add some Typedoc/JSDoc comments on the new `RateRule` and `RatePolicy` to indicate that this is out-of-spec for MDS 0.4.1. Dunno if there's a keyword for indicating something as not-officially-supported yet (basically the "future" version of `@deprecated`), but I'll look around!

**Review by twelch — APPROVED** [review]
Agree a comment as Neil notes would be helpful

**Comment by janedotx** [comment]
Just curious, why merge into `develop`? `rate_amount` is a 1.0 thing, so why not `dev/upgrade-to-1.0`?

**Comment by avatarneil** [comment]
> Just curious, why merge into `develop`? `rate_amount` is a 1.0 thing, so why not `dev/upgrade-to-1.0`?

@janedotx we need this for OtherThings™️ which are higher priority than the 1.0.0 merge

**Review by janedotx — APPROVED** [review]

**Comment by BigIdeas** [comment]
> Rad! I think we ought to add some Typedoc/JSDoc comments on the new `RateRule` and `RatePolicy` to indicate that this is out-of-spec for MDS 0.4.1. Dunno if there's a keyword for indicating something as not-officially-supported yet (basically the "future" version of `@deprecated`), but I'll look around!

Doesn't look like there's a Typedoc tag that suits this use case, so I just slapped an `alpha` tag on them. Think that makes sense?

Screen Shot 2020-11-05 at 11 31 49 AM
Screen Shot 2020-11-05 at 11 31 05 AM

**Pull request merged**
