### PR TITLE
MDSAAS-275 Remove AWS Lambda handlers, etc.

### PR DESCRIPTION
**Pull request by drtyh2o**
MDS Core now runs on Kubernetes! Onward!! Woot Woot!

### CODE REVIEW

**Comment by karcass** [comment]
This is blocked because of a couple of daily-report lambdas, yeah?

**Comment by avatarneil** [comment]
@karcass _Technically_ yes, however we're not really doing much in the way of active dev on the daily report lambdas. We can just bring back the lambda handlers temporarily on a local machine using git-magic if we need to deploy a new version to hotfix anything.

**Comment by drtyh2o** [comment]
> This is blocked because of a couple of daily-report lambdas, yeah?

Well, technically the lambdas will continue to run, but we will no longer be able to update/deploy them there once this merges (unless we do so from a branch that's behind `develop`). I don't mind keeping this open and updated until the scheduled jobs are running on kube if the above is a concern. Or we can go ahead and merge it to speed up builds.

**Comment by karcass** [comment]
However you want to drive it.  I'm definitely a burn-the-ships guy.

**Comment by drtyh2o** [comment]
It will keep running on AWS until we shut it down. Neil is working on the kube replacement. We can always hotfix/patch it in a crisis. As long as Alex is cool with where we are with kube (I don't see us reverting back at this point) then it sounds to me like we should 🔥the 🚢and merge it in.

**Pull request merged**
