### PR TITLE
[draft] [helm/mds] : fully qualify object names

### PR DESCRIPTION
**Pull request by jwtodd**
**status:** hold on this as helm:3 changes things in this regard, we do not want to merge this patch just yet, given the cross-cutting concerns

**note:** the recent change to add `$api.version` to the ( auth, ingress and service ) objects has the impact of making the service-endpoint no longer durable across deployment revisions ... which has pros and cons we need to work through.
 
in order to better support rolling updates in addition to supporting best-practices this patch fully-qualifies object names following the pattern:

for a pod amongst many pods:
  [release-name]-[service-name]-[service-version]-[kind]-[pod-id]

for a singular kind (eg secret):
  [release-name]-[kind]

eg:

```
% kubectl get pods -n mds`
mds-mds-agency-0.1.17-unstable-deployment-6dd47b7869-4kwbw   1/2     Running   0          32m
mds-postgresql-0                                             2/2     Running   0          32m
mds-redis-master-0                                           2/2     Running   0          32m
```

verify:

```
% curl http://localhost/agency -i
HTTP/1.1 200 OK
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 181
etag: W/"b5-epLd3niuGijnZVg9g9ILs/FwReI"
date: Tue, 05 Nov 2019 21:52:33 GMT
x-envoy-upstream-service-time: 5
server: istio-envoy

{"name":"@container-images/mds-agency","version":"0.1.17","build":{"date":"2019-10-30T17:37:49.285Z","branch":"mocha-ts-ftw","commit":"c814b45"},"node":"10.16.3","status":"Running"}
```
## PR Checklist

 - [ ] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
 - [ ] briefly describe the changes in this PR
 - [ ] mark as draft if should not be merged
 - [ ] write tests for all new functionality

## Impacts
- [ ] Provider
- [ ] Agency
- [ ] Audit
- [ ] Policy
- [ ] Compliance
- [ ] Daily
- [ ] Native
- [ ] Policy Author

### CODE REVIEW

**Comment by jwtodd** [comment]
@invertigo ready for another round of reviews, noting an externally initiated curl resolved as expected this time around.

**Comment by jwtodd** [comment]
@playground-julia the mds service endpoint name changes with this patch and as such the default simulator-helm-host property will need to be provided.

this is how `mdsctl` overrides said configuration: https://github.com/lacuna-tech/mds-core/blob/feature/jwtodd-k8s-object-fullname/bin/mdsctl#L88

**Comment by jwtodd** [comment]
@avatarneil the recent patch adds $api.version transform(. -> -) to the service-ids ... should we want to include it. tested fine locally.

**Comment by evanxadkins** [comment]
Looks good.

**Comment by jwtodd** [comment]
defer

**Pull request closed without merging**
