### PR TITLE
[mds-modality-policy] [mds-modality-policy-author] [helm] Update docker image names & helm templates for new mds-policy packages

### PR DESCRIPTION
**Pull request by avatarneil**
## 📚 Purpose
Due to the recent changes made around Policy where we now have `mds-modality-policy` and `mds-modality-policy-author` instead of just `mds-policy` and `mds-policy-author`, there was a need to update the image tagging & helm deployments accordingly.

## 👌 Resolves:
- being unable to deploy using scripts

## 📦 Impacts:
- @container-images/mds-modality-policy
- @container-images/mds-modality-policy-author
- helm stuff

## ✅ PR Checklist
- [x] Test that `pnpm values` works properly

### CODE REVIEW

**Review by drtyh2o — COMMENTED** [review]
I am confused by this. Why was `@container-images/mds-policy` deleted, but not `@container-images/mds-policy-author`? Do these new packages replace the old ones or are they in addition to them?

**Review by janedotx — APPROVED** [review]
opes

**Comment by janedotx** [comment]
> I am confused by this. Why was `@container-images/mds-policy` deleted, but not `@container-images/mds-policy-author`? Do these new packages replace the old ones or are they in addition to them?

It's probably best to think of `@container-images/mds-policy` and `@container-images/mds-policy-author` as being replaced by the `mds-modality` equivalents.

**Comment by drtyh2o** [comment]
> > I am confused by this. Why was `@container-images/mds-policy` deleted, but not `@container-images/mds-policy-author`? Do these new packages replace the old ones or are they in addition to them?
> 
> It's probably best to think of `@container-images/mds-policy` and `@container-images/mds-policy-author` as being replaced by the `mds-modality` equivalents.

Right. Shouldn’t the original policy author container also be deleted then?

**Review by drtyh2o — APPROVED** [review]

**Pull request merged**
