### PR TITLE
Update prettier config to enforce single quotes only in js/ts files, since we may want to have double quotes in yaml files.

### PR DESCRIPTION
**Pull request by janedotx**
## PR Checklist

 - [ ] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
 - [ ] briefly describe the changes in this PR
 - [ ] mark as draft if should not be merged
 - [ ] write tests for all new functionality

## Impacts
- [ ] Provider
- [ ] Agency
- [ ] Audit
- [ ] Policy
- [ ] Compliance
- [ ] Daily
- [ ] Native
- [ ] Policy Author

### CODE REVIEW

**Comment by avatarneil** [comment]
What about making this exclusive versus inclusive? Have the default be single quotes, and then make it so only for yaml files we'll ignore that rule. Something like:

```json
{
  "arrowParens": "avoid",
  "printWidth": 120,
  "semi": false,
  "tabWidth": 2,
  "trailingComma": "none",
   "singleQuote": true
  "overrides": [
    {
      "files": ["*.yaml"],
      "options": {
        "singleQuote": false
      }
    }
  ]
}
```

**Comment by drtyh2o** [comment]
Do we even want to run Prettier on .yaml files at all? I worry about running a formatter on something where indentation is significant. Maybe we should set the `files` option to only format `.ts`

**Comment by avatarneil** [comment]
> Do we even want to run Prettier on .yaml files at all? I worry about running a formatter on something where indentation is significant. Maybe we should set the `files` option to only format `.ts`

I still think it'd be nice to keep it more on the exclusive side -- so we could just do something like `"prettier.disableLanguages": ["yaml"]` Cc. @drtyh2o @janedotx

**Comment by macsj200** [comment]
I'd think we'd want prettier to leave all other files alone, perhaps we can add `*.yaml` to `.prettierignore`.

**Comment by janedotx** [comment]
> What about making this exclusive versus inclusive? Have the default be single quotes, and then make it so only for yaml files we'll ignore that rule. Something like:
> 
> ```js
> {
>   "arrowParens": "avoid",
>   "printWidth": 120,
>   "semi": false,
>   "tabWidth": 2,
>   "trailingComma": "none",
>   "singleQuote": true
>   "overrides": [
>     {
>       "files": ["*.yaml"],
>       "options": {
>         "singleQuote": false
>       }
>     }
>   ]
> }
> ```

I think we know for a fact that we care most about the formatting of js/ts files. We have a lot of other miscellaneous file types, like `yaml.tpl` or `bin/mdsctl`, where the formatting standards might be different.

**Comment by janedotx** [comment]
This is a blocker for merging the mds-config and mds-config-service removal, by the way, since to the best of my knowledge, the single-quoted yaml files are due to our current prettier configuration.

**Comment by avatarneil** [comment]
@janedotx This is not a blocker... If the files were formatted properly, they can be formatted properly again. Just cmd+shift+p -> save without formatting

**Comment by avatarneil** [comment]
> > What about making this exclusive versus inclusive? Have the default be single quotes, and then make it so only for yaml files we'll ignore that rule. Something like:
> > ```js
> > {
> >   "arrowParens": "avoid",
> >   "printWidth": 120,
> >   "semi": false,
> >   "tabWidth": 2,
> >   "trailingComma": "none",
> >   "singleQuote": true
> >   "overrides": [
> >     {
> >       "files": ["*.yaml"],
> >       "options": {
> >         "singleQuote": false
> >       }
> >     }
> >   ]
> > }
> > ```
> 
> I think we know for a fact that we're most opinionated about the formatting of js/ts files. We have a lot of other miscellaneous file types, like `yaml.tpl` or `bin/mdsctl`, where the formatting standards might be different. Inclusive makes the most sense to me, cause if we went exclusive, that might be a lot of file types that have to be explicitly excluded.

In that case, we should be only formatting js/ts files at all; get rid of the `overrides` and just set `files` at the top level to only apply our formatting rules to `["*.js", "*.ts", "*.tsx", "*.json", "*.json5"]`

**Comment by janedotx** [comment]
> @janedotx This is not a blocker... If the files were formatted properly, they can be formatted properly again. Just cmd+shift+p -> save without formatting

Oh interesting, I didn't know that VSCode had that option.

**Pull request merged**
